/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamepkg;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author aa
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    static StringBuffer val=new StringBuffer("");
    String level;
    int score=0;
    public GamePanel(String lvl) {
        initComponents();
        level=lvl;
        lblmsg.setText("Level: "+lvl);
        lblscore.setText(score+""); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnumber2 = new javax.swing.JButton();
        btnnumber3 = new javax.swing.JButton();
        btnnumber5 = new javax.swing.JButton();
        btnnumber6 = new javax.swing.JButton();
        btnnumber8 = new javax.swing.JButton();
        btnnumber9 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnnumber0 = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        btnnumber1 = new javax.swing.JButton();
        btnnumber4 = new javax.swing.JButton();
        btnnumber7 = new javax.swing.JButton();
        txtusernumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblmsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblscore = new javax.swing.JLabel();
        lblresult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblusernumber = new javax.swing.JLabel();
        lblrandomnumber = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(null);

        btnnumber2.setText("2");
        btnnumber2.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber2.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber2.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber2ActionPerformed(evt);
            }
        });
        add(btnnumber2);
        btnnumber2.setBounds(224, 140, 45, 29);

        btnnumber3.setText("3");
        btnnumber3.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber3.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber3.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber3ActionPerformed(evt);
            }
        });
        add(btnnumber3);
        btnnumber3.setBounds(287, 140, 45, 29);

        btnnumber5.setText("5");
        btnnumber5.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber5.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber5.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber5ActionPerformed(evt);
            }
        });
        add(btnnumber5);
        btnnumber5.setBounds(224, 187, 45, 29);

        btnnumber6.setText("6");
        btnnumber6.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber6.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber6.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber6ActionPerformed(evt);
            }
        });
        add(btnnumber6);
        btnnumber6.setBounds(287, 187, 45, 29);

        btnnumber8.setText("8");
        btnnumber8.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber8.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber8.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber8ActionPerformed(evt);
            }
        });
        add(btnnumber8);
        btnnumber8.setBounds(224, 234, 45, 29);

        btnnumber9.setText("9");
        btnnumber9.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber9.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber9.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber9ActionPerformed(evt);
            }
        });
        add(btnnumber9);
        btnnumber9.setBounds(287, 234, 45, 29);

        btnclear.setText("clr");
        btnclear.setMaximumSize(new java.awt.Dimension(40, 29));
        btnclear.setMinimumSize(new java.awt.Dimension(40, 29));
        btnclear.setPreferredSize(new java.awt.Dimension(45, 29));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        add(btnclear);
        btnclear.setBounds(161, 281, 45, 29);

        btnnumber0.setText("0");
        btnnumber0.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber0.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber0.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber0ActionPerformed(evt);
            }
        });
        add(btnnumber0);
        btnnumber0.setBounds(224, 281, 45, 29);

        btnok.setText("ok");
        btnok.setMaximumSize(new java.awt.Dimension(40, 29));
        btnok.setMinimumSize(new java.awt.Dimension(40, 29));
        btnok.setPreferredSize(new java.awt.Dimension(45, 29));
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        add(btnok);
        btnok.setBounds(287, 281, 45, 29);

        btnnumber1.setText("1");
        btnnumber1.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber1.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber1.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber1ActionPerformed(evt);
            }
        });
        add(btnnumber1);
        btnnumber1.setBounds(161, 140, 45, 29);

        btnnumber4.setText("4");
        btnnumber4.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber4.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber4.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber4ActionPerformed(evt);
            }
        });
        add(btnnumber4);
        btnnumber4.setBounds(161, 187, 45, 29);

        btnnumber7.setText("7");
        btnnumber7.setMaximumSize(new java.awt.Dimension(40, 29));
        btnnumber7.setMinimumSize(new java.awt.Dimension(40, 29));
        btnnumber7.setPreferredSize(new java.awt.Dimension(45, 29));
        btnnumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber7ActionPerformed(evt);
            }
        });
        add(btnnumber7);
        btnnumber7.setBounds(161, 234, 45, 29);
        add(txtusernumber);
        txtusernumber.setBounds(390, 140, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        add(jLabel1);
        jLabel1.setBounds(249, 58, 57, 17);

        lblmsg.setForeground(new java.awt.Color(255, 255, 255));
        lblmsg.setText("Level:");
        add(lblmsg);
        lblmsg.setBounds(21, 58, 75, 37);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("For Easy : Range is 0-5 For Medium : Range is 0-10 For Hard Range is 0-15");
        add(jLabel2);
        jLabel2.setBounds(80, 340, 420, 86);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Score:");
        add(jLabel4);
        jLabel4.setBounds(390, 250, 120, 14);

        lblscore.setForeground(new java.awt.Color(255, 255, 255));
        lblscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblscore.setText("0");
        lblscore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblscore);
        lblscore.setBounds(487, 250, 62, 14);

        lblresult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblresult.setForeground(new java.awt.Color(255, 0, 0));
        lblresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblresult);
        lblresult.setBounds(390, 270, 160, 50);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Your Number");
        add(jLabel3);
        jLabel3.setBounds(390, 187, 110, 14);

        jLabel5.setForeground(new java.awt.Color(102, 255, 51));
        jLabel5.setText("Generated Number");
        add(jLabel5);
        jLabel5.setBounds(390, 220, 120, 14);

        lblusernumber.setForeground(new java.awt.Color(255, 255, 0));
        lblusernumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusernumber.setText("0");
        add(lblusernumber);
        lblusernumber.setBounds(487, 187, 62, 14);

        lblrandomnumber.setForeground(new java.awt.Color(102, 255, 51));
        lblrandomnumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrandomnumber.setText("0");
        add(lblrandomnumber);
        lblrandomnumber.setBounds(487, 220, 62, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamepkg/mybkg2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        val.delete(0, val.length());
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber1ActionPerformed
        // TODO add your handling code here:
        val.append("1");
        txtusernumber.setText( val.toString());
        
    }//GEN-LAST:event_btnnumber1ActionPerformed

    private void btnnumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber2ActionPerformed
        // TODO add your handling code here:
        val.append("2");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber2ActionPerformed

    private void btnnumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber3ActionPerformed
        // TODO add your handling code here:
        val.append("3");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber3ActionPerformed

    private void btnnumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber4ActionPerformed
        // TODO add your handling code here:
        val.append("4");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber4ActionPerformed

    private void btnnumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber5ActionPerformed
        // TODO add your handling code here:
        val.append("5");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber5ActionPerformed

    private void btnnumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber6ActionPerformed
        // TODO add your handling code here:
        val.append("6");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber6ActionPerformed

    private void btnnumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber7ActionPerformed
        // TODO add your handling code here:
        val.append("7");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber7ActionPerformed

    private void btnnumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber8ActionPerformed
        // TODO add your handling code here:
        val.append("8");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber8ActionPerformed

    private void btnnumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber9ActionPerformed
        // TODO add your handling code here:
        val.append("9");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber9ActionPerformed

    private void btnnumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber0ActionPerformed
        // TODO add your handling code here:
        val.append("0");
        txtusernumber.setText( val.toString());
    }//GEN-LAST:event_btnnumber0ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        String str1=txtusernumber.getText();
        if(str1.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter Number");
        }
        else
        {
        int range;
        
        Random rndm=new Random();
        
        switch (level) {
            case "Easy":
                range=5;
                break;
            case "Medium":
                range=10;
                break;
            case "Hard":
                range=15;
                break;
            default:
                range=5;
                break;
        }
        
       lblusernumber.setText(str1);
       lblrandomnumber.setText(String.valueOf(rndm.nextInt(range)));
        
        
        String str2=lblrandomnumber.getText();
        
        if(str1.equals(str2))
        {
            score++;
            lblscore.setText(score+"");
            lblresult.setText("you won");
           
        }
        
        else
        {
            lblresult.setText("you lost");
            
        }
        
        //--------------- Clearing textboxes
        val.delete(0, val.length());
        txtusernumber.setText( val.toString());
        
        //--------------------
    }//GEN-LAST:event_btnokActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnnumber0;
    private javax.swing.JButton btnnumber1;
    private javax.swing.JButton btnnumber2;
    private javax.swing.JButton btnnumber3;
    private javax.swing.JButton btnnumber4;
    private javax.swing.JButton btnnumber5;
    private javax.swing.JButton btnnumber6;
    private javax.swing.JButton btnnumber7;
    private javax.swing.JButton btnnumber8;
    private javax.swing.JButton btnnumber9;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JLabel lblrandomnumber;
    private javax.swing.JLabel lblresult;
    private javax.swing.JLabel lblscore;
    private javax.swing.JLabel lblusernumber;
    private javax.swing.JTextField txtusernumber;
    // End of variables declaration//GEN-END:variables
}
