/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamepkg;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import java.util.*;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JMenu;
import javax.swing.JRadioButton;

/**
 *
 * @author aa
 */
public class LevelPanel extends javax.swing.JPanel {

    /**
     * Creates new form LevelPanel
     */
    JPanel basepanel;
    String username;
    JMenu menugoto;
    public LevelPanel(JPanel basepanel,String username,JMenu menugoto) {
        initComponents();
        this.basepanel=basepanel;
        this.username=username;
        this.menugoto=menugoto;
        
        menugoto.setEnabled(true);
        
     //   jLabel1.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton1.setForeground(java.awt.Color.white);
        jRadioButton1.setText("Easy");
        jRadioButton1.setOpaque(false);
        add(jRadioButton1);
        jRadioButton1.setBounds(247, 194, 90, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton2.setForeground(java.awt.Color.white);
        jRadioButton2.setText("Medium");
        jRadioButton2.setOpaque(false);
        add(jRadioButton2);
        jRadioButton2.setBounds(247, 236, 110, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton3.setForeground(java.awt.Color.white);
        jRadioButton3.setText("Hard");
        jRadioButton3.setOpaque(false);
        add(jRadioButton3);
        jRadioButton3.setBounds(247, 278, 90, 25);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(247, 348, 109, 25);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Select Level");
        add(jLabel2);
        jLabel2.setBounds(237, 99, 190, 29);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamepkg/bkgoriginal.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str="";
        int level=1;
        
        Enumeration<AbstractButton> allbtn=buttonGroup1.getElements();
        while(allbtn.hasMoreElements())
        {
            JRadioButton temp=(JRadioButton)allbtn.nextElement();
            if(temp.isSelected())
            {
                str=temp.getText();
            }
        }
        
        if(str.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Select a level");
        }
        else
        {
            
        
         if(str=="Easy")
        {
             level=1;
        }
        if(str=="Medium")
        {
            level=2;
        }
        if(str=="Hard")
        {
            level=3;
        }
        
            
            GamePanel2 gp=new GamePanel2(level,username);
            basepanel.removeAll();
            basepanel.add(gp);
            basepanel.validate();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
