/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamepkg;

import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aa
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JPanel basepanel;
    JMenu menugoto;
    public LoginPanel() {
        initComponents();
    }

    public LoginPanel(JPanel basepanel,JMenu menugoto)
    {
        initComponents();
        this.basepanel=basepanel;
        this.menugoto=menugoto;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(170, 180, 80, 17);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(170, 220, 90, 17);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        add(jLabel3);
        jLabel3.setBounds(230, 90, 120, 43);

        btnsubmit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        add(btnsubmit);
        btnsubmit.setBounds(260, 300, 72, 25);

        txtusername.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(txtusername);
        txtusername.setBounds(320, 170, 120, 23);

        txtpassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(txtpassword);
        txtpassword.setBounds(320, 220, 120, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamepkg/bkgoriginal.png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String username=txtusername.getText();
        String password=String.valueOf(txtpassword.getPassword());
       
        
        if(username.length()==0 || password.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Enter Username/Passord");
        }
        
        else
        {
          
            LevelPanel levelpanel=new LevelPanel(basepanel,username,menugoto);
            basepanel.removeAll();
            basepanel.add(levelpanel);
            basepanel.validate();
             
            
        }
    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
