/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamepkg;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Admin
 */
public class SignupPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupPanel
     */
    public SignupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtrepassword = new javax.swing.JPasswordField();
        combocountry = new javax.swing.JComboBox();
        txtdob = new javax.swing.JFormattedTextField();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        txtzipcode = new javax.swing.JFormattedTextField();
        btnsubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New User");
        add(jLabel1);
        jLabel1.setBounds(230, 60, 140, 22);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(130, 120, 97, 22);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOB");
        add(jLabel3);
        jLabel3.setBounds(130, 150, 97, 22);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        add(jLabel4);
        jLabel4.setBounds(130, 180, 97, 22);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        add(jLabel5);
        jLabel5.setBounds(130, 210, 97, 22);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        add(jLabel6);
        jLabel6.setBounds(130, 240, 97, 22);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Re-password");
        add(jLabel7);
        jLabel7.setBounds(130, 270, 97, 22);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Country");
        add(jLabel8);
        jLabel8.setBounds(130, 300, 97, 22);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Zip code");
        add(jLabel9);
        jLabel9.setBounds(130, 330, 97, 22);

        txtfname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtfname.setText("FirstName");
        txtfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfnameFocusLost(evt);
            }
        });
        add(txtfname);
        txtfname.setBounds(250, 117, 97, 22);

        txtlname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtlname.setText("LastName");
        txtlname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlnameFocusLost(evt);
            }
        });
        add(txtlname);
        txtlname.setBounds(353, 117, 97, 22);

        txtusername.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add(txtusername);
        txtusername.setBounds(250, 203, 97, 22);

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtpassword);
        txtpassword.setBounds(250, 234, 97, 22);

        txtrepassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtrepassword);
        txtrepassword.setBounds(250, 265, 97, 22);

        combocountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(combocountry);
        combocountry.setBounds(250, 296, 97, 22);

        txtdob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdobFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdobFocusLost(evt);
            }
        });
        add(txtdob);
        txtdob.setBounds(250, 150, 97, 22);

        rbtnmale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnmale);
        rbtnmale.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rbtnmale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnmale.setText("Male");
        rbtnmale.setOpaque(false);
        add(rbtnmale);
        rbtnmale.setBounds(250, 180, 97, 22);

        rbtnfemale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnfemale);
        rbtnfemale.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rbtnfemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnfemale.setText("Female");
        rbtnfemale.setOpaque(false);
        add(rbtnfemale);
        rbtnfemale.setBounds(350, 180, 97, 22);
        add(txtzipcode);
        txtzipcode.setBounds(250, 327, 97, 22);

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        add(btnsubmit);
        btnsubmit.setBounds(250, 370, 97, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamepkg/bkgoriginal.png"))); // NOI18N
        jLabel10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel10FocusGained(evt);
            }
        });
        add(jLabel10);
        jLabel10.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
       
        StringBuffer str=new StringBuffer("");
        String usr=txtusername.getText();
        String pass=String.valueOf(txtpassword.getPassword());
        String dob=String.valueOf(txtdob.getText());
        String repass=String.valueOf(txtrepassword.getPassword());
        String fname=txtfname.getText();
        String lname=txtlname.getText();
        String zipcode=txtzipcode.getText();
        String rbtn="";
        String str1="FirstName";
        String str2="LastName";
        
        Enumeration<AbstractButton> button=buttonGroup1.getElements();
        while(button.hasMoreElements())
        {
             JRadioButton  temp=(JRadioButton)button.nextElement();
            if(temp.isSelected()){
                System.out.println(temp.getText());
                rbtn=temp.getText();
            }
        }
        if(fname.equals(str1)||lname.equals(str2))
        {
            str.append("Enter Name");
        }
        else if(dob.isEmpty()){
              str.append("Invalid DOB\n");
             
        }
         else if(rbtn.isEmpty()){
             str.append("Select Gender\n");
        }
       
         else if(usr.isEmpty()){
          str.append("Enter Username\n");
                   
        }
        else if(pass.isEmpty()){
             str.append("Enter Password\n");
             
        }
        else if(pass.length()<4){
            str.append("Password should be more than 4 characters\n");
        }
        else if(!pass.equals(repass)){
              str.append("Password Mismatch\n");
        }
        
        else if(zipcode.isEmpty()){
             str.append("Invalid Zipcode\n");
        }
       
        
        else
            str.append("Successful ");
        
        JOptionPane.showMessageDialog(null, str);
        
        
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed
  
    private void txtfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusGained
        // TODO add your handling code here:
        
        String str1="FirstName";
        String str2=txtfname.getText();
        if(str2.equals(str1))
        {
            txtfname.setText("");
        }
    }//GEN-LAST:event_txtfnameFocusGained

    private void txtfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusLost
        // TODO add your handling code here:
         String str1="FirstName";
        String str2=txtfname.getText();
        if(str2.isEmpty())
        {
            txtfname.setText(str1);
        }
        
    }//GEN-LAST:event_txtfnameFocusLost

    private void txtlnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnameFocusGained
        // TODO add your handling code here:
        
        String str1="LastName";
        String str2=txtlname.getText();
        if(str2.equals(str1))
        {
            txtlname.setText("");
        }
    }//GEN-LAST:event_txtlnameFocusGained

    private void txtlnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnameFocusLost
        // TODO add your handling code here:
        String str1="LastName";
        String str2=txtlname.getText();
        if(str2.isEmpty())
        {
            txtlname.setText(str1);
        }
    }//GEN-LAST:event_txtlnameFocusLost

    private void jLabel10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10FocusGained

    private void txtdobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusGained
        // TODO add your handling code here:
        
        
        ///check on submit
    }//GEN-LAST:event_txtdobFocusGained

    private void txtdobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtdobFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combocountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private javax.swing.JFormattedTextField txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtrepassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JFormattedTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
}
